// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map_uid_counts.proto
package ONLINE.ProtocolBuffer;
public final class map_uid_counts_Protobuf {
  private map_uid_counts_Protobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface map_uid_countsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:map_uid_counts)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
     */
    int getUidCountsCount();
    /**
     * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
     */
    boolean containsUidCounts(
        int key);
    /**
     * Use {@link #getUidCountsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.Long>
    getUidCounts();
    /**
     * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Long>
    getUidCountsMap();
    /**
     * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
     */

    long getUidCountsOrDefault(
        int key,
        long defaultValue);
    /**
     * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
     */

    long getUidCountsOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code map_uid_counts}
   */
  public  static final class map_uid_counts extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:map_uid_counts)
      map_uid_countsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use map_uid_counts.newBuilder() to construct.
    private map_uid_counts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private map_uid_counts() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private map_uid_counts(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                uidCounts_ = com.google.protobuf.MapField.newMapField(
                    UidCountsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
              uidCounts__ = input.readMessage(
                  UidCountsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              uidCounts_.getMutableMap().put(
                  uidCounts__.getKey(), uidCounts__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return map_uid_counts_Protobuf.internal_static_map_uid_counts_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetUidCounts();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return map_uid_counts_Protobuf.internal_static_map_uid_counts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              map_uid_counts_Protobuf.map_uid_counts.class, map_uid_counts_Protobuf.map_uid_counts.Builder.class);
    }

    public static final int UID_COUNTS_FIELD_NUMBER = 1;
    private static final class UidCountsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Long> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Long>newDefaultInstance(
                  map_uid_counts_Protobuf.internal_static_map_uid_counts_UidCountsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Long> uidCounts_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
    internalGetUidCounts() {
      if (uidCounts_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            UidCountsDefaultEntryHolder.defaultEntry);
      }
      return uidCounts_;
    }

    public int getUidCountsCount() {
      return internalGetUidCounts().getMap().size();
    }
    /**
     * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
     */

    public boolean containsUidCounts(
        int key) {
      
      return internalGetUidCounts().getMap().containsKey(key);
    }
    /**
     * Use {@link #getUidCountsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Long> getUidCounts() {
      return getUidCountsMap();
    }
    /**
     * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Long> getUidCountsMap() {
      return internalGetUidCounts().getMap();
    }
    /**
     * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
     */

    public long getUidCountsOrDefault(
        int key,
        long defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Long> map =
          internalGetUidCounts().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
     */

    public long getUidCountsOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Long> map =
          internalGetUidCounts().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetUidCounts(),
          UidCountsDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Long> entry
           : internalGetUidCounts().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
        uidCounts__ = UidCountsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, uidCounts__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof map_uid_counts_Protobuf.map_uid_counts)) {
        return super.equals(obj);
      }
      map_uid_counts_Protobuf.map_uid_counts other = (map_uid_counts_Protobuf.map_uid_counts) obj;

      if (!internalGetUidCounts().equals(
          other.internalGetUidCounts())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetUidCounts().getMap().isEmpty()) {
        hash = (37 * hash) + UID_COUNTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetUidCounts().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static map_uid_counts_Protobuf.map_uid_counts parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static map_uid_counts_Protobuf.map_uid_counts parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static map_uid_counts_Protobuf.map_uid_counts parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static map_uid_counts_Protobuf.map_uid_counts parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static map_uid_counts_Protobuf.map_uid_counts parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static map_uid_counts_Protobuf.map_uid_counts parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static map_uid_counts_Protobuf.map_uid_counts parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static map_uid_counts_Protobuf.map_uid_counts parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static map_uid_counts_Protobuf.map_uid_counts parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static map_uid_counts_Protobuf.map_uid_counts parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static map_uid_counts_Protobuf.map_uid_counts parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static map_uid_counts_Protobuf.map_uid_counts parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(map_uid_counts_Protobuf.map_uid_counts prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code map_uid_counts}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:map_uid_counts)
        map_uid_counts_Protobuf.map_uid_countsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return map_uid_counts_Protobuf.internal_static_map_uid_counts_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetUidCounts();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableUidCounts();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return map_uid_counts_Protobuf.internal_static_map_uid_counts_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                map_uid_counts_Protobuf.map_uid_counts.class, map_uid_counts_Protobuf.map_uid_counts.Builder.class);
      }

      // Construct using map_uid_counts_Protobuf.map_uid_counts.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableUidCounts().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return map_uid_counts_Protobuf.internal_static_map_uid_counts_descriptor;
      }

      @java.lang.Override
      public map_uid_counts_Protobuf.map_uid_counts getDefaultInstanceForType() {
        return map_uid_counts_Protobuf.map_uid_counts.getDefaultInstance();
      }

      @java.lang.Override
      public map_uid_counts_Protobuf.map_uid_counts build() {
        map_uid_counts_Protobuf.map_uid_counts result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public map_uid_counts_Protobuf.map_uid_counts buildPartial() {
        map_uid_counts_Protobuf.map_uid_counts result = new map_uid_counts_Protobuf.map_uid_counts(this);
        int from_bitField0_ = bitField0_;
        result.uidCounts_ = internalGetUidCounts();
        result.uidCounts_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof map_uid_counts_Protobuf.map_uid_counts) {
          return mergeFrom((map_uid_counts_Protobuf.map_uid_counts)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(map_uid_counts_Protobuf.map_uid_counts other) {
        if (other == map_uid_counts_Protobuf.map_uid_counts.getDefaultInstance()) return this;
        internalGetMutableUidCounts().mergeFrom(
            other.internalGetUidCounts());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        map_uid_counts_Protobuf.map_uid_counts parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (map_uid_counts_Protobuf.map_uid_counts) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Long> uidCounts_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
      internalGetUidCounts() {
        if (uidCounts_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              UidCountsDefaultEntryHolder.defaultEntry);
        }
        return uidCounts_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
      internalGetMutableUidCounts() {
        onChanged();;
        if (uidCounts_ == null) {
          uidCounts_ = com.google.protobuf.MapField.newMapField(
              UidCountsDefaultEntryHolder.defaultEntry);
        }
        if (!uidCounts_.isMutable()) {
          uidCounts_ = uidCounts_.copy();
        }
        return uidCounts_;
      }

      public int getUidCountsCount() {
        return internalGetUidCounts().getMap().size();
      }
      /**
       * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
       */

      public boolean containsUidCounts(
          int key) {
        
        return internalGetUidCounts().getMap().containsKey(key);
      }
      /**
       * Use {@link #getUidCountsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Long> getUidCounts() {
        return getUidCountsMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
       */

      public java.util.Map<java.lang.Integer, java.lang.Long> getUidCountsMap() {
        return internalGetUidCounts().getMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
       */

      public long getUidCountsOrDefault(
          int key,
          long defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.Long> map =
            internalGetUidCounts().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
       */

      public long getUidCountsOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.Long> map =
            internalGetUidCounts().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearUidCounts() {
        internalGetMutableUidCounts().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
       */

      public Builder removeUidCounts(
          int key) {
        
        internalGetMutableUidCounts().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Long>
      getMutableUidCounts() {
        return internalGetMutableUidCounts().getMutableMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
       */
      public Builder putUidCounts(
          int key,
          long value) {
        
        
        internalGetMutableUidCounts().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, int64&gt; uid_counts = 1;</code>
       */

      public Builder putAllUidCounts(
          java.util.Map<java.lang.Integer, java.lang.Long> values) {
        internalGetMutableUidCounts().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:map_uid_counts)
    }

    // @@protoc_insertion_point(class_scope:map_uid_counts)
    private static final map_uid_counts_Protobuf.map_uid_counts DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new map_uid_counts_Protobuf.map_uid_counts();
    }

    public static map_uid_counts_Protobuf.map_uid_counts getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<map_uid_counts>
        PARSER = new com.google.protobuf.AbstractParser<map_uid_counts>() {
      @java.lang.Override
      public map_uid_counts parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new map_uid_counts(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<map_uid_counts> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<map_uid_counts> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public map_uid_counts_Protobuf.map_uid_counts getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_map_uid_counts_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_map_uid_counts_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_map_uid_counts_UidCountsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_map_uid_counts_UidCountsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024map_uid_counts.proto\"v\n\016map_uid_counts" +
      "\0222\n\nuid_counts\030\001 \003(\0132\036.map_uid_counts.Ui" +
      "dCountsEntry\0320\n\016UidCountsEntry\022\013\n\003key\030\001 " +
      "\001(\005\022\r\n\005value\030\002 \001(\003:\0028\001B\031B\027map_uid_counts" +
      "_Protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_map_uid_counts_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_map_uid_counts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_map_uid_counts_descriptor,
        new java.lang.String[] { "UidCounts", });
    internal_static_map_uid_counts_UidCountsEntry_descriptor =
      internal_static_map_uid_counts_descriptor.getNestedTypes().get(0);
    internal_static_map_uid_counts_UidCountsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_map_uid_counts_UidCountsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
